### ISSUE TITLE
Getting exception

### ISSUE THREAD

**Issue by anil1712** [evan-carey/angular-typescript-webpack#1]
Hi,

I am getting below exception while running the application
```
bootstrap ab09cfb…:633 Uncaught Error: Cannot find module "./src/app/vendor.ts"
    at webpackMissingModule (bootstrap ab09cfb…:633)


client?cd17:37 [WDS] Hot Module Replacement enabled.
client?cd17:37 [WDS] Errors while compiling.
client?cd17:75 ./src/app/index.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (C:\xampp\htdocs\github\angular-typescript-webpack\node_modules\awesome-typescript-loader\src\instance.ts:266:72)
    at Object.ensureInstance (C:\xampp\htdocs\github\angular-typescript-webpack\node_modules\awesome-typescript-loader\src\instance.ts:145:5)
    at compiler (C:\xampp\htdocs\github\angular-typescript-webpack\node_modules\awesome-typescript-loader\src\index.ts:37:20)
    at Object.loader (C:\xampp\htdocs\github\angular-typescript-webpack\node_modules\awesome-typescript-loader\src\index.ts:18:18)
 @ multi app
errors @ client?cd17:75
sock.onmessage @ socket.js:37
EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:274
SockJS._transportMessage @ main.js:272
EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
client?cd17:75 ./src/app/vendor.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (C:\xampp\htdocs\github\angular-typescript-webpack\node_modules\awesome-typescript-loader\src\instance.ts:266:72)
    at Object.ensureInstance (C:\xampp\htdocs\github\angular-typescript-webpack\node_modules\awesome-typescript-loader\src\instance.ts:145:5)
    at compiler (C:\xampp\htdocs\github\angular-typescript-webpack\node_modules\awesome-typescript-loader\src\index.ts:37:20)
    at Object.loader (C:\xampp\htdocs\github\angular-typescript-webpack\node_modules\awesome-typescript-loader\src\index.ts:18:18)
 @ multi vendor

```
Please help me to resolve this issue

Thanks

**Comment by aboudard** [comment]
Hello
I fixed this particuler error by changing some versions
awesome-typescript-loader : 2.2.4 >> 3.0.3
typescript : 2.03 >> 2.1.4

BUT I now have issues with ui-router :(

**Comment by evan-carey** [comment]
Hi,
I just released a new version that tightens the dependency versions, which resolved the issue for me. Let me know if it works for you.
(When I have more free time, I'll go through and update the project to use Angular 1.6, Webpack 2, and TypeScript 2.3)

Thanks

**Comment by aboudard** [comment]
Fine by me, works just fine now !
Thank you :)

**Comment by anil1712** [comment]
Thanks @evan-carey for solution but I am geting issue in `npm run build` command
Getting this exception
```
Error in bail mode: [default] C:\dashboard-app\node_modules\@types\angular-cookies\index.d.ts:9:25
Cannot find module 'angular'.
```
Is anyone having this kind of issue?
